CREATE TABLE accounts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    account_type VARCHAR(255) NOT NULL,
    initial_balance NUMERIC(19, 2) NOT NULL,
    balance NUMERIC(19, 2) NOT NULL,
    user_id BIGINT NOT NULL,
    account_status VARCHAR(255) NOT NULL,
    create_date TIMESTAMP(6) NOT NULL,
    modified_date TIMESTAMP(6),
    CONSTRAINT fk_accounts_user
        FOREIGN KEY (user_id) REFERENCES users (id),
    CONSTRAINT chk_accounts_account_type
        CHECK (account_type IN (
            'CONTA_CORRENTE',
            'CONTA_POUPANCA',
            'CARTEIRA',
            'CARTAO_CREDITO',
            'INVESTIMENTO'
        )),
    CONSTRAINT chk_accounts_account_status
        CHECK (account_status IN ('ATIVA', 'INATIVA'))
);
